### ISSUE TITLE
Move schemes to colors/ subfolder

### ISSUE THREAD

**Issue by anddam** [twerth/ir_black#1]
You may want to move the theme files to a colors subfolder so the repository is ready to be cloned when using a vim plugin manager like pathogen. 

edit:
https://github.com/wgibbs/vim-irblack already does, I suggested the owner to fork his repo from this one.

**Comment by twerth** [comment]
Done, thanks for the suggestion.

**Comment by anddam** [comment]
You're welcome, thanks for the theme.
